language: objective-c

xcode_project: Themeable.xcodeproj
osx_image: xcode9.2
env: SCHEME="Themeable"

install:
  - carthage update --platform iOS
    
script:
  - xcodebuild clean build -project Themeable.xcodeproj -scheme $SCHEME
